export type WordBankScope = 1 | 2 | 3;

export type WordGroup = {
  words: readonly [string, string, ...string[]];
  category: string;
  difficulty: WordBankScope;
};

// 词库由“同分类词组”组成，而不是固定搭配好的“平民词/卧底词”。
// 每组是一个 { words, category } 对象：words 里至少两个词可以任意互换，
// 发牌时随机挑两个，再随机决定谁当平民词、谁当卧底词。
// 三个数组分别对应难度 1/2/3（简单/普通/挑战）。
// 简单：高频、具体、差异明显；普通：同类词或需要一定常识；挑战：近邻概念、专业术语或文化辨析。
type WordGroupEntry = { words: readonly [string, string, ...string[]]; category: string };

function createWordGroups(difficulty: WordBankScope, entries: readonly WordGroupEntry[]): WordGroup[] {
  return entries.map((entry) => ({ words: entry.words, category: entry.category, difficulty }));
}

const EASY_WORD_GROUPS: readonly WordGroupEntry[] = [
  { words: ["咖啡", "奶茶"], category: "饮品" },
  { words: ["可乐", "雪碧"], category: "碳酸饮料" },
  { words: ["橙汁", "苹果汁"], category: "果汁" },
  { words: ["牛奶", "酸奶"], category: "乳制品" },
  { words: ["绿茶", "红茶"], category: "茶饮" },
  { words: ["豆浆", "米浆"], category: "谷物饮品" },
  { words: ["柠檬水", "苏打水"], category: "清爽饮品" },
  { words: ["啤酒", "红酒"], category: "酒类" },
  { words: ["热巧克力", "热牛奶"], category: "热饮" },
  { words: ["矿泉水", "纯净水"], category: "瓶装水" },
  { words: ["米饭", "面条"], category: "主食" },
  { words: ["馒头", "包子"], category: "面点" },
  { words: ["饺子", "馄饨"], category: "面食" },
  { words: ["炒饭", "炒面"], category: "快餐主食" },
  { words: ["粥", "米线"], category: "早餐主食" },
  { words: ["汉堡", "三明治"], category: "西式快餐" },
  { words: ["披萨", "意面"], category: "西式餐点" },
  { words: ["蛋糕", "面包"], category: "烘焙" },
  { words: ["油条", "烧饼"], category: "早餐面点" },
  { words: ["月饼", "粽子"], category: "节日食品" },
  { words: ["火锅", "烧烤"], category: "聚餐美食" },
  { words: ["麻婆豆腐", "鱼香肉丝"], category: "川菜" },
  { words: ["宫保鸡丁", "糖醋里脊"], category: "家常菜" },
  { words: ["番茄炒蛋", "青椒肉丝"], category: "家常炒菜" },
  { words: ["红烧肉", "回锅肉"], category: "猪肉菜" },
  { words: ["清蒸鱼", "红烧鱼"], category: "鱼类菜肴" },
  { words: ["炸鸡", "烤鸡"], category: "鸡肉料理" },
  { words: ["牛排", "羊排"], category: "肉排" },
  { words: ["寿司", "刺身"], category: "日式料理" },
  { words: ["拉面", "乌冬面"], category: "日式面食" },
  { words: ["苹果", "梨"], category: "常见水果" },
  { words: ["香蕉", "芒果"], category: "热带水果" },
  { words: ["西瓜", "哈密瓜"], category: "瓜果" },
  { words: ["葡萄", "樱桃"], category: "小型水果" },
  { words: ["草莓", "蓝莓"], category: "浆果" },
  { words: ["橘子", "柚子"], category: "柑橘" },
  { words: ["菠萝", "木瓜"], category: "热带水果" },
  { words: ["桃子", "李子"], category: "核果" },
  { words: ["黄瓜", "西葫芦"], category: "瓜类蔬菜" },
  { words: ["西红柿", "彩椒"], category: "果实蔬菜" },
  { words: ["猫", "狗"], category: "宠物" },
  { words: ["兔子", "仓鼠"], category: "小型宠物" },
  { words: ["金鱼", "乌龟"], category: "水族宠物" },
  { words: ["狮子", "老虎"], category: "猫科动物" },
  { words: ["大象", "犀牛"], category: "大型动物" },
  { words: ["熊猫", "考拉"], category: "珍稀动物" },
  { words: ["猴子", "猩猩"], category: "灵长类" },
  { words: ["斑马", "长颈鹿"], category: "草原动物" },
  { words: ["海豚", "鲸鱼"], category: "海洋哺乳动物" },
  { words: ["企鹅", "海鸥"], category: "海鸟" },
  { words: ["衬衫", "毛衣"], category: "上装" },
  { words: ["外套", "风衣"], category: "外套" },
  { words: ["裙子", "短裤"], category: "夏装" },
  { words: ["牛仔裤", "运动裤"], category: "裤装" },
  { words: ["皮鞋", "运动鞋"], category: "鞋类" },
  { words: ["拖鞋", "凉鞋"], category: "夏季鞋" },
  { words: ["帽子", "围巾"], category: "配饰" },
  { words: ["手套", "袜子"], category: "保暖配件" },
  { words: ["领带", "领结"], category: "正装配饰" },
  { words: ["雨衣", "雨靴"], category: "雨具穿戴" },
  { words: ["铅笔", "圆珠笔"], category: "书写工具" },
  { words: ["橡皮", "修正带"], category: "文具" },
  { words: ["书包", "笔袋"], category: "学习收纳" },
  { words: ["课本", "练习册"], category: "学习资料" },
  { words: ["黑板", "白板"], category: "教学用品" },
  { words: ["尺子", "量角器"], category: "绘图工具" },
  { words: ["剪刀", "胶水"], category: "手工工具" },
  { words: ["订书机", "打孔器"], category: "办公工具" },
  { words: ["电脑", "平板"], category: "数码设备" },
  { words: ["键盘", "鼠标"], category: "电脑配件" },
  { words: ["公交车", "地铁"], category: "城市交通" },
  { words: ["自行车", "电动车"], category: "两轮交通" },
  { words: ["飞机", "直升机"], category: "航空交通" },
  { words: ["轮船", "游艇"], category: "水上交通" },
  { words: ["轿车", "越野车"], category: "汽车" },
  { words: ["救护车", "消防车"], category: "特种车辆" },
  { words: ["货车", "面包车"], category: "商用车辆" },
  { words: ["摩托车", "踏板车"], category: "机动两轮" },
  { words: ["医院", "诊所"], category: "医疗场所" },
  { words: ["学校", "幼儿园"], category: "教育场所" },
  { words: ["超市", "便利店"], category: "零售场所" },
  { words: ["银行", "邮局"], category: "公共服务" },
  { words: ["图书馆", "书店"], category: "阅读场所" },
  { words: ["电影院", "剧院"], category: "演出场所" },
  { words: ["公园", "植物园"], category: "休闲场所" },
  { words: ["动物园", "海洋馆"], category: "观赏场馆" },
  { words: ["餐厅", "咖啡馆"], category: "餐饮场所" },
  { words: ["酒店", "民宿"], category: "住宿场所" },
  { words: ["春天", "秋天"], category: "季节" },
  { words: ["夏天", "冬天"], category: "季节" },
  { words: ["晴天", "阴天"], category: "天气" },
  { words: ["下雨", "下雪"], category: "天气" },
  { words: ["彩虹", "晚霞"], category: "天空景象" },
  { words: ["云朵", "雾气"], category: "大气现象" },
  { words: ["河流", "湖泊"], category: "水域" },
  { words: ["山峰", "峡谷"], category: "地貌" },
  { words: ["沙滩", "泳池"], category: "水上休闲" },
  { words: ["床", "沙发"], category: "家具" },
  { words: ["书桌", "餐桌"], category: "桌子" },
  { words: ["衣柜", "书柜"], category: "收纳家具" },
  { words: ["窗帘", "百叶窗"], category: "窗饰" },
  { words: ["枕头", "被子"], category: "寝具" },
  { words: ["台灯", "吊灯"], category: "照明" },
  { words: ["冰箱", "洗衣机"], category: "家电" },
  { words: ["微波炉", "烤箱"], category: "厨房电器" },
  { words: ["空调", "电风扇"], category: "制冷电器" },
  { words: ["扫把", "拖把"], category: "清洁工具" },
  { words: ["眼睛", "耳朵"], category: "感官" },
  { words: ["鼻子", "嘴巴"], category: "五官" },
  { words: ["牙齿", "舌头"], category: "口腔" },
  { words: ["手臂", "小腿"], category: "四肢" },
  { words: ["心脏", "肺部"], category: "器官" },
  { words: ["感冒", "发烧"], category: "常见病" },
  { words: ["咳嗽", "打喷嚏"], category: "呼吸症状" },
  { words: ["口罩", "护目镜"], category: "防护用品" },
  { words: ["创可贴", "纱布"], category: "急救用品" },
  { words: ["足球", "篮球"], category: "球类运动" },
  { words: ["羽毛球", "乒乓球"], category: "小球运动" },
  { words: ["网球", "排球"], category: "球类运动" },
  { words: ["跑步", "跳绳"], category: "健身运动" },
  { words: ["游泳", "潜水"], category: "水上运动" },
  { words: ["滑雪", "滑冰"], category: "冰雪运动" },
  { words: ["瑜伽", "普拉提"], category: "室内健身" },
  { words: ["拳击", "跆拳道"], category: "格斗运动" },
  { words: ["登山", "徒步"], category: "户外运动" },
  { words: ["骑马", "骑行"], category: "户外运动" },
  { words: ["电影", "电视剧"], category: "影视形式" },
  { words: ["动画片", "纪录片"], category: "影视类型" },
  { words: ["小说", "漫画"], category: "阅读作品" },
  { words: ["歌曲", "舞曲"], category: "音乐类型" },
  { words: ["吉他", "钢琴"], category: "乐器" },
  { words: ["小提琴", "大提琴"], category: "弦乐器" },
  { words: ["相机", "摄像机"], category: "影像设备" },
  { words: ["扑克牌", "麻将"], category: "桌面游戏" },
  { words: ["积木", "拼图"], category: "益智玩具" },
  { words: ["话筒", "音响"], category: "音乐设备" },
  { words: ["医生", "护士"], category: "医疗职业" },
  { words: ["老师", "校长"], category: "教育职业" },
  { words: ["警察", "保安"], category: "安保职业" },
  { words: ["厨师", "服务员"], category: "餐饮职业" },
  { words: ["司机", "快递员"], category: "运输职业" },
  { words: ["记者", "编辑"], category: "媒体职业" },
  { words: ["画家", "摄影师"], category: "艺术职业" },
  { words: ["律师", "法官"], category: "司法职业" },
  { words: ["程序员", "设计师"], category: "互联网职业" },
  { words: ["农民", "园丁"], category: "种植职业" },
  { words: ["行李箱", "背包"], category: "旅行收纳" },
  { words: ["护照", "签证"], category: "出境证件" },
  { words: ["地图", "导航"], category: "旅行指引" },
  { words: ["车票", "登机牌"], category: "出行凭证" },
  { words: ["帐篷", "睡袋"], category: "露营用品" },
  { words: ["望远镜", "指南针"], category: "户外工具" },
  { words: ["泳衣", "救生圈"], category: "海边用品" },
  { words: ["防晒霜", "太阳镜"], category: "防晒用品" },
  { words: ["纪念品", "明信片"], category: "旅行纪念" },
  { words: ["肥皂", "洗手液"], category: "清洁用品" },
  { words: ["牙刷", "牙膏"], category: "洗漱用品" },
  { words: ["洗发水", "沐浴露"], category: "洗浴用品" },
  { words: ["香水", "护肤品"], category: "美容用品" },
  { words: ["蜡烛", "打火机"], category: "点火用品" },
  { words: ["钟表", "闹钟"], category: "计时工具" },
  { words: ["现金", "银行卡"], category: "支付工具" },
  { words: ["礼物", "贺卡"], category: "节日礼品" },
  { words: ["布丁", "果冻"], category: "甜品" },
  { words: ["玻璃杯", "保温杯"], category: "杯具" },
  { words: ["红色", "蓝色", "绿色", "黄色"], category: "颜色" },
  { words: ["东", "南", "西", "北"], category: "方位" },
  { words: ["喜剧片", "动作片", "科幻片", "恐怖片"], category: "电影类型" },
  { words: ["红桃", "黑桃", "梅花", "方块"], category: "扑克牌花色" },
  { words: ["飞行棋", "跳棋"], category: "棋类游戏" },
  { words: ["筷子", "勺子"], category: "餐具" },
  { words: ["番茄酱", "沙拉酱"], category: "酱料" },
  { words: ["马克笔", "彩笔"], category: "绘画文具" },
  { words: ["手风琴", "电子琴"], category: "键盘乐器" },
  { words: ["麻辣烫", "关东煮", "串串香"], category: "街边小吃" },
  { words: ["酸梅汤", "绿豆汤"], category: "消暑饮品" },
  { words: ["麻薯", "糯米糍"], category: "软糯点心" },
  { words: ["抹布", "鸡毛掸子"], category: "除尘工具" },
  { words: ["床垫", "床单"], category: "寝具" },
  { words: ["邮递员", "外卖员"], category: "配送职业" },
  { words: ["警察局", "消防站"], category: "公共机构" },
  { words: ["踢毽子", "跳皮筋"], category: "童年游戏" },
  { words: ["洗碗机", "消毒柜"], category: "厨房电器" },
  { words: ["眉毛", "睫毛"], category: "面部细节" },
  { words: ["老鹰", "燕子", "麻雀", "喜鹊"], category: "常见鸟类" },
  { words: ["蜘蛛侠", "钢铁侠", "美国队长", "雷神", "绿巨人", "黑寡妇", "奇异博士", "黑豹", "鹰眼", "蚁人"], category: "漫威超级英雄" },
  { words: ["密码", "指纹"], category: "解锁方式" },
  { words: ["清晨", "傍晚"], category: "一日时段" },
  { words: ["昨天", "明天"], category: "时间" },
  { words: ["周末", "假期"], category: "休闲时间" },
  { words: ["东边", "西边"], category: "方位" },
  { words: ["左边", "右边"], category: "方位" },
  { words: ["远处", "近处"], category: "距离" },
  { words: ["楼上", "楼下"], category: "楼层方位" },
  { words: ["白糖", "红糖"], category: "糖类" },
  { words: ["食盐", "味精"], category: "调味品" },
  { words: ["花生", "瓜子"], category: "坚果零食" },
  { words: ["薯片", "爆米花"], category: "休闲零食" },
  { words: ["巧克力", "糖果"], category: "甜食" },
  { words: ["纸巾", "湿巾"], category: "清洁纸品" },
  { words: ["餐叉", "餐刀"], category: "西式餐具" },
  { words: ["茄子", "冬瓜"], category: "家常蔬菜" },
  { words: ["手链", "项链"], category: "饰品" },
  { words: ["猫粮", "狗粮"], category: "宠物食品" },
  { words: ["轮椅", "拐杖"], category: "辅助器具" },
  { words: ["故宫", "长城", "兵马俑", "西湖"], category: "知名景点" },
  { words: ["红楼梦", "三国演义", "水浒传", "西游记"], category: "古典名著" },
  { words: ["诗歌", "散文"], category: "文学体裁" },
  { words: ["春节", "元宵节"], category: "传统节日" },
  { words: ["清明节", "端午节"], category: "传统节日" },
  { words: ["中秋节", "重阳节"], category: "传统节日" },
  { words: ["笔记本电脑", "台式电脑"], category: "电脑设备" },
  { words: ["无线耳机", "有线耳机"], category: "耳机" },
  { words: ["手机壳", "手机膜"], category: "手机配件" },
  { words: ["日出", "日落"], category: "天文景象" },
  { words: ["微风", "大风"], category: "风力" },
  { words: ["月光", "星光"], category: "夜间光线" },
  { words: ["山脚", "山顶"], category: "山体方位" },
  { words: ["花盆", "花瓶"], category: "容器" },
  { words: ["夜市", "集市"], category: "市集" },
  { words: ["种子", "幼苗"], category: "植物生长" },
  { words: ["合唱", "独唱"], category: "歌唱形式" },
  { words: ["河马", "犀牛"], category: "非洲动物" },
  { words: ["土豆", "胡萝卜", "白萝卜", "大白菜"], category: "常见蔬菜" },
  { words: ["菠菜", "生菜", "油麦菜", "空心菜"], category: "叶菜" },
  { words: ["香菇", "金针菇", "平菇", "杏鲍菇"], category: "食用菌" },
  { words: ["猪肉", "牛肉", "羊肉", "鸡肉"], category: "常见肉类" },
  { words: ["大虾", "螃蟹", "海鱼", "蛤蜊"], category: "常见海鲜" },
  { words: ["饼干", "威化饼", "蛋卷", "沙琪玛"], category: "休闲点心" },
  { words: ["冰淇淋", "奶昔", "双皮奶", "奶冻"], category: "奶味甜品" },
  { words: ["汤圆", "元宵", "年糕", "青团"], category: "糯米食品" },
  { words: ["紫菜蛋花汤", "冬瓜汤", "排骨汤", "鸡汤"], category: "家常汤" },
  { words: ["盘子", "碟子", "饭碗", "汤碗"], category: "餐具" },
  { words: ["菜刀", "锅铲", "漏勺", "打蛋器"], category: "厨房工具" },
  { words: ["客厅", "卧室", "厨房", "卫生间"], category: "住宅房间" },
  { words: ["阳台", "玄关", "走廊", "楼梯"], category: "住宅区域" },
  { words: ["椅子", "凳子", "长椅", "躺椅"], category: "座椅" },
  { words: ["毛巾", "浴巾", "浴帽", "浴袍"], category: "洗浴用品" },
  { words: ["垃圾桶", "垃圾袋", "清洁刷", "除尘纸"], category: "清洁用品" },
  { words: ["爷爷", "奶奶", "外公", "外婆"], category: "祖辈称呼" },
  { words: ["哥哥", "姐姐", "弟弟", "妹妹"], category: "兄弟姐妹" },
  { words: ["语文", "数学", "英语", "体育"], category: "学校科目" },
  { words: ["音乐课", "美术课", "科学课", "信息技术课"], category: "学校课程" },
  { words: ["讲台", "课桌", "粉笔", "板擦"], category: "教室用品" },
  { words: ["教室", "操场", "食堂", "宿舍"], category: "校园场所" },
  { words: ["太阳", "月亮", "星星", "云彩"], category: "天空事物" },
  { words: ["森林", "草原", "沙漠", "海洋"], category: "自然环境" },
  { words: ["黄牛", "奶牛", "家猪", "家兔"], category: "农场动物" },
  { words: ["公鸡", "母鸡", "鸭子", "鹅"], category: "家禽" },
  { words: ["蛇", "蜥蜴", "鳄鱼", "壁虎"], category: "爬行动物" },
  { words: ["蚊子", "苍蝇", "瓢虫", "蟋蟀"], category: "常见昆虫" },
  { words: ["乌鸦", "鸽子", "百灵鸟", "布谷鸟"], category: "常见鸟类" },
  { words: ["紫色", "粉色", "橙色", "棕色", "黑色", "白色"], category: "颜色" },
  { words: ["圆形", "方形", "三角形", "长方形"], category: "形状" },
  { words: ["微笑", "大笑", "哭泣", "皱眉"], category: "表情" },
  { words: ["开心", "难过", "生气", "害怕"], category: "常见情绪" },
  { words: ["刷牙", "洗脸", "洗澡", "洗头"], category: "个人清洁" },
  { words: ["做饭", "洗碗", "扫地", "晒衣服"], category: "家务" },
  { words: ["微信", "贴吧", "微博", "小红书", "抖音", "哔哩哔哩"], category: "社交与内容平台" },
  { words: ["淘宝", "京东", "拼多多", "闲鱼"], category: "购物平台" },
  { words: ["爱奇艺", "腾讯视频", "优酷", "芒果TV"], category: "视频平台" },
  { words: ["QQ音乐", "网易云音乐", "酷狗音乐", "酷我音乐"], category: "音乐平台" },
  { words: ["图片", "视频", "音频", "文档"], category: "文件内容" },
  { words: ["复制", "粘贴", "保存", "删除"], category: "电脑操作" },
  { words: ["拍照", "录像", "扫码", "录音"], category: "手机功能" },
  { words: ["中国", "日本", "韩国", "泰国"], category: "亚洲国家" },
  { words: ["英国", "法国", "德国", "意大利"], category: "欧洲国家" },
  { words: ["北京", "上海", "广州", "深圳"], category: "中国大城市" },
  { words: ["机场", "火车站", "汽车站", "地铁站"], category: "交通枢纽" },
  { words: ["劳动节", "国庆节", "儿童节", "教师节"], category: "常见节日" },
  { words: ["开学", "放假", "考试", "毕业"], category: "校园事件" },
  { words: ["握手", "拥抱", "挥手", "敬礼"], category: "社交动作" },
  { words: ["额头", "脸颊", "下巴", "酒窝"], category: "面部部位" },
  { words: ["肩膀", "膝盖", "脚踝", "手腕"], category: "身体关节" },
  { words: ["头痛", "肚子痛", "牙痛", "喉咙痛"], category: "常见不适" },
  { words: ["捉迷藏", "老鹰捉小鸡", "丢手绢", "木头人"], category: "童年游戏" },
  { words: ["熊出没", "喜羊羊与灰太狼", "猪猪侠", "大头儿子和小头爸爸", "超级飞侠"], category: "国产动画" },
  { words: ["白雪公主", "灰姑娘", "小红帽", "睡美人", "匹诺曹"], category: "童话人物" },
  { words: ["孙悟空", "猪八戒", "哪吒", "二郎神", "牛魔王"], category: "中国神话人物" },
  { words: ["超人", "蝙蝠侠", "神奇女侠", "闪电侠", "海王", "绿灯侠"], category: "DC超级英雄" },
  { words: ["武林外传", "家有儿女", "爱情公寓", "炊事班的故事"], category: "经典情景喜剧" },
  { words: ["疯狂动物城", "冰雪奇缘", "功夫熊猫", "寻梦环游记"], category: "热门动画电影" },
  { words: ["植物大战僵尸", "愤怒的小鸟", "水果忍者", "神庙逃亡"], category: "经典休闲游戏" },
  { words: ["王者荣耀", "英雄联盟", "和平精英", "穿越火线"], category: "热门竞技游戏" },
  { words: ["斗地主", "狼人杀", "谁是卧底", "你画我猜"], category: "聚会游戏" },
  { words: ["鼠", "牛", "虎", "兔", "龙", "蛇", "马", "羊", "猴", "鸡", "狗", "猪"], category: "十二生肖" },
  { words: ["亚洲", "欧洲", "非洲", "北美洲", "南美洲", "大洋洲", "南极洲"], category: "七大洲" },
  { words: ["太平洋", "大西洋", "印度洋", "北冰洋", "南冰洋"], category: "五大洋" },
  { words: ["水星", "金星", "地球", "火星", "木星", "土星", "天王星", "海王星"], category: "太阳系行星" },
  { words: ["金牌", "银牌", "铜牌"], category: "比赛奖牌" },
  { words: ["第一名", "第二名", "第三名"], category: "比赛名次" },
];

const STANDARD_WORD_GROUPS: readonly WordGroupEntry[] = [
  { words: ["奶酪", "黄油"], category: "乳制食材" },
  { words: ["蜂蜜", "糖浆"], category: "甜味调料" },
  { words: ["酱油", "醋"], category: "调味料" },
  { words: ["花椒", "胡椒"], category: "香辛料" },
  { words: ["豆腐", "豆皮"], category: "豆制品" },
  { words: ["虾仁", "蟹肉"], category: "海鲜食材" },
  { words: ["牛腩", "牛腱"], category: "牛肉部位" },
  { words: ["五花肉", "里脊肉"], category: "猪肉部位" },
  { words: ["鸡翅", "鸡腿"], category: "鸡肉部位" },
  { words: ["酸菜鱼", "水煮鱼"], category: "川味鱼菜" },
  { words: ["烤鸭", "盐水鸭"], category: "鸭肉菜" },
  { words: ["东坡肉", "梅菜扣肉"], category: "猪肉菜" },
  { words: ["烧卖", "小笼包"], category: "点心" },
  { words: ["肠粉", "河粉"], category: "米制面食" },
  { words: ["凉皮", "米皮"], category: "凉拌主食" },
  { words: ["螺蛳粉", "桂林米粉"], category: "地方面食" },
  { words: ["铜锣烧", "鲷鱼烧"], category: "日式点心" },
  { words: ["可颂", "法棍"], category: "欧式面包" },
  { words: ["松树", "柏树"], category: "针叶树" },
  { words: ["柳树", "榕树"], category: "常见树木" },
  { words: ["玫瑰", "月季"], category: "蔷薇花" },
  { words: ["荷花", "睡莲"], category: "水生花卉" },
  { words: ["向日葵", "雏菊"], category: "花卉" },
  { words: ["竹子", "芦苇"], category: "高杆植物" },
  { words: ["仙人掌", "多肉植物"], category: "耐旱植物" },
  { words: ["枫叶", "银杏叶"], category: "秋叶" },
  { words: ["稻田", "麦田"], category: "农田" },
  { words: ["瀑布", "泉水"], category: "自然水景" },
  { words: ["狼", "狐狸"], category: "犬科动物" },
  { words: ["松鼠", "花栗鼠"], category: "啮齿动物" },
  { words: ["马", "驴"], category: "家畜" },
  { words: ["山羊", "绵羊"], category: "羊类" },
  { words: ["骆驼", "羊驼"], category: "驼科动物" },
  { words: ["孔雀", "鸵鸟"], category: "大型鸟类" },
  { words: ["鹦鹉", "八哥"], category: "会说话的鸟" },
  { words: ["海龟", "海豹"], category: "海洋动物" },
  { words: ["章鱼", "乌贼"], category: "软体动物" },
  { words: ["蝴蝶", "蜻蜓"], category: "昆虫" },
  { words: ["吸尘器", "扫地机器人"], category: "清洁电器" },
  { words: ["电饭煲", "压力锅"], category: "烹饪电器" },
  { words: ["榨汁机", "破壁机"], category: "厨房小电器" },
  { words: ["吹风机", "卷发棒"], category: "美发电器" },
  { words: ["加湿器", "空气净化器"], category: "空气电器" },
  { words: ["电热毯", "暖手宝"], category: "取暖用品" },
  { words: ["门铃", "猫眼"], category: "门口设备" },
  { words: ["衣架", "晾衣杆"], category: "晾晒用品" },
  { words: ["砧板", "擀面杖"], category: "厨房工具" },
  { words: ["保鲜盒", "密封袋"], category: "食品收纳" },
  { words: ["钢笔", "毛笔"], category: "书写工具" },
  { words: ["便签纸", "信纸"], category: "书写纸品" },
  { words: ["文件夹", "档案盒"], category: "文件收纳" },
  { words: ["打印机", "复印机"], category: "办公设备" },
  { words: ["投影仪", "电子白板"], category: "教学设备" },
  { words: ["日历", "计划本"], category: "时间管理" },
  { words: ["计算器", "算盘"], category: "计算工具" },
  { words: ["显微镜", "放大镜"], category: "观察工具" },
  { words: ["试管", "烧杯"], category: "实验器材" },
  { words: ["图钉", "回形针"], category: "固定文具" },
  { words: ["手机", "智能手表"], category: "智能设备" },
  { words: ["耳机", "耳麦"], category: "音频设备" },
  { words: ["充电宝", "充电器"], category: "充电设备" },
  { words: ["硬盘", "闪存盘"], category: "存储设备" },
  { words: ["显示器", "投影幕"], category: "显示设备" },
  { words: ["遥控器", "游戏手柄"], category: "控制设备" },
  { words: ["摄像头", "扫描仪"], category: "采集设备" },
  { words: ["站台", "候车室"], category: "车站区域" },
  { words: ["机票", "船票"], category: "旅行票证" },
  { words: ["驾驶证", "行驶证"], category: "车辆证件" },
  { words: ["红绿灯", "斑马线"], category: "交通设施" },
  { words: ["方向盘", "安全带"], category: "汽车部件" },
  { words: ["油门", "刹车"], category: "车辆控制" },
  { words: ["独木舟", "皮划艇"], category: "水上器材" },
  { words: ["滑板", "轮滑鞋"], category: "轮滑运动" },
  { words: ["缆车", "索道"], category: "山地交通" },
  { words: ["菜市场", "农贸市场"], category: "农产品市场" },
  { words: ["药店", "眼镜店"], category: "专业商店" },
  { words: ["美术馆", "博物馆"], category: "展览场馆" },
  { words: ["体育馆", "健身房"], category: "运动场所" },
  { words: ["游乐园", "水上乐园"], category: "游乐场所" },
  { words: ["停车场", "加油站"], category: "车辆服务" },
  { words: ["理发店", "美容院"], category: "美容场所" },
  { words: ["洗衣店", "裁缝店"], category: "衣物服务" },
  { words: ["社区", "街道"], category: "居住区域" },
  { words: ["码头", "港口"], category: "水运场所" },
  { words: ["血压计", "体温计"], category: "健康测量" },
  { words: ["听诊器", "血糖仪"], category: "医疗工具" },
  { words: ["维生素", "钙片"], category: "营养补充" },
  { words: ["退烧药", "止咳药"], category: "常用药物" },
  { words: ["牙线", "漱口水"], category: "口腔护理" },
  { words: ["护手霜", "润唇膏"], category: "护理用品" },
  { words: ["洗面奶", "卸妆水"], category: "护肤清洁" },
  { words: ["面膜", "眼霜"], category: "护肤用品" },
  { words: ["体重秤", "卷尺"], category: "身体测量" },
  { words: ["水彩", "油画"], category: "画材" },
  { words: ["素描", "速写"], category: "绘画方式" },
  { words: ["国画", "书法"], category: "传统艺术" },
  { words: ["雕塑", "陶艺"], category: "立体艺术" },
  { words: ["戏曲", "歌剧"], category: "舞台艺术" },
  { words: ["芭蕾", "现代舞"], category: "舞蹈" },
  { words: ["小号", "长笛"], category: "管乐器" },
  { words: ["鼓", "锣"], category: "打击乐器" },
  { words: ["童话", "寓言"], category: "文学体裁" },
  { words: ["棒球", "垒球"], category: "棒类运动" },
  { words: ["冲浪", "帆板"], category: "水上运动" },
  { words: ["射箭", "飞镖"], category: "投掷运动" },
  { words: ["保龄球", "台球"], category: "室内球类" },
  { words: ["赛跑", "接力跑"], category: "田径项目" },
  { words: ["马拉松", "越野跑"], category: "长跑项目" },
  { words: ["攀岩", "抱石"], category: "岩壁运动" },
  { words: ["太极拳", "八段锦"], category: "传统健身" },
  { words: ["举重", "力量训练"], category: "力量运动" },
  { words: ["婚礼", "订婚仪式"], category: "婚庆活动" },
  { words: ["生日会", "毕业典礼"], category: "庆祝活动" },
  { words: ["邀请函", "请柬"], category: "活动文书" },
  { words: ["对联", "福字"], category: "新年装饰" },
  { words: ["灯笼", "彩灯"], category: "节庆装饰" },
  { words: ["红包", "礼金"], category: "祝贺礼物" },
  { words: ["纪念册", "相册"], category: "回忆载体" },
  { words: ["会计", "出纳"], category: "财务职业" },
  { words: ["建筑师", "工程师"], category: "建设职业" },
  { words: ["飞行员", "空乘"], category: "航空职业" },
  { words: ["导游", "领队"], category: "旅游职业" },
  { words: ["演员", "导演"], category: "影视职业" },
  { words: ["主持人", "播音员"], category: "媒体职业" },
  { words: ["消防员", "救援员"], category: "应急职业" },
  { words: ["牙医", "药剂师"], category: "医疗职业" },
  { words: ["裁缝", "理发师"], category: "手艺职业" },
  { words: ["科学家", "研究员"], category: "科研职业" },
  { words: ["记忆", "想象"], category: "思维活动" },
  { words: ["计划", "目标"], category: "行动规划" },
  { words: ["习惯", "规律"], category: "生活方式" },
  { words: ["选择", "决定"], category: "决策" },
  { words: ["秘密", "谎言"], category: "信息状态" },
  { words: ["道歉", "感谢"], category: "社交表达" },
  { words: ["勇气", "耐心"], category: "品质" },
  { words: ["兴奋", "紧张"], category: "情绪" },
  { words: ["诚实", "善良"], category: "品质" },
  { words: ["成功", "进步"], category: "成果" },
  { words: ["午夜", "黎明"], category: "夜间时段" },
  { words: ["平年", "闰年"], category: "年份" },
  { words: ["上旬", "下旬"], category: "月份时段" },
  { words: ["蜡笔", "彩铅"], category: "绘画文具" },
  { words: ["瓷碗", "玻璃碗"], category: "餐具" },
  { words: ["保温壶", "热水瓶"], category: "保温容器" },
  { words: ["泰山", "华山", "衡山", "恒山", "嵩山"], category: "名山" },
  { words: ["扇贝", "生蚝"], category: "贝类海鲜" },
  { words: ["刀削面", "烩面"], category: "手工面食" },
  { words: ["背带裤", "连体裤"], category: "裤装" },
  { words: ["无人机", "遥控飞机"], category: "遥控设备" },
  { words: ["净水器", "饮水机"], category: "饮用水设备" },
  { words: ["炒锅", "平底锅"], category: "锅具" },
  { words: ["挂钩", "收纳盒"], category: "居家收纳" },
  { words: ["头灯", "手电筒"], category: "露营照明" },
  { words: ["信用卡", "储蓄卡"], category: "支付工具" },
  { words: ["简历", "面试"], category: "求职环节" },
  { words: ["庙会", "花市"], category: "年俗活动" },
  { words: ["演唱会", "音乐节"], category: "现场演出" },
  { words: ["立交桥", "隧道"], category: "道路设施" },
  { words: ["藏羚羊", "金丝猴", "东北虎", "朱鹮"], category: "中国珍稀动物" },
  { words: ["水煮肉片", "毛血旺", "剁椒鱼头"], category: "川湘菜" },
  { words: ["白羊座", "金牛座", "双子座", "巨蟹座", "狮子座", "处女座", "天秤座", "天蝎座", "射手座", "摩羯座", "水瓶座", "双鱼座"], category: "十二星座" },
  { words: ["立春", "雨水", "惊蛰", "春分", "清明", "谷雨"], category: "春季节气" },
  { words: ["立夏", "小满", "芒种", "夏至", "小暑", "大暑"], category: "夏季节气" },
  { words: ["立秋", "处暑", "白露", "秋分", "寒露", "霜降"], category: "秋季节气" },
  { words: ["立冬", "小雪", "大雪", "冬至", "小寒", "大寒"], category: "冬季节气" },
  { words: ["出租车", "网约车"], category: "叫车服务" },
  { words: ["火车", "高铁"], category: "铁路交通" },
  { words: ["雨伞", "遮阳伞"], category: "伞具" },
  { words: ["野餐", "郊游"], category: "户外活动" },
  { words: ["五子棋", "围棋"], category: "棋类游戏" },
  { words: ["七夕节", "情人节"], category: "爱情节日" },
  { words: ["眼镜", "隐形眼镜"], category: "视力矫正" },
  { words: ["风筝", "孔明灯"], category: "天空玩具" },
  { words: ["乌龙茶", "普洱茶"], category: "茶叶" },
  { words: ["威士忌", "白兰地"], category: "洋酒" },
  { words: ["豆奶", "燕麦奶"], category: "植物奶" },
  { words: ["羽绒服", "棉服"], category: "冬装" },
  { words: ["连衣裙", "半身裙"], category: "裙装" },
  { words: ["针织衫", "卫衣"], category: "休闲上装" },
  { words: ["耳环", "耳钉"], category: "耳饰" },
  { words: ["游戏主机", "掌上游戏机"], category: "游戏设备" },
  { words: ["笔记本", "活页本"], category: "书写本" },
  { words: ["便签本", "待办清单"], category: "记录工具" },
  { words: ["签字笔", "中性笔"], category: "书写工具" },
  { words: ["荧光笔", "记号笔"], category: "标记笔" },
  { words: ["固体胶", "双面胶"], category: "粘贴用品" },
  { words: ["胶带", "封箱胶"], category: "粘贴用品" },
  { words: ["资料夹", "文件袋"], category: "文件收纳" },
  { words: ["打孔机", "装订机"], category: "办公工具" },
  { words: ["云海", "雾凇"], category: "天气景观" },
  { words: ["流星", "彗星"], category: "天空天体" },
  { words: ["潮汐", "海浪"], category: "海洋现象" },
  { words: ["盆地", "高原"], category: "地貌" },
  { words: ["海狮", "海象"], category: "海洋哺乳动物" },
  { words: ["海豚", "虎鲸"], category: "鲸豚" },
  { words: ["啄木鸟", "翠鸟"], category: "鸟类" },
  { words: ["蜜蜂", "黄蜂"], category: "昆虫" },
  { words: ["露营地", "房车营地"], category: "户外住宿" },
  { words: ["购物中心", "百货商店"], category: "零售场所" },
  { words: ["温泉馆", "汗蒸馆"], category: "休闲场所" },
  { words: ["健身房", "瑜伽馆"], category: "运动场所" },
  { words: ["公路自行车", "山地自行车"], category: "骑行装备" },
  { words: ["网球拍", "羽毛球拍"], category: "球拍" },
  { words: ["赛艇", "皮划艇"], category: "划船运动" },
  { words: ["短跑", "跨栏"], category: "田径项目" },
  { words: ["深蹲", "硬拉"], category: "力量训练" },
  { words: ["冥想", "呼吸训练"], category: "身心训练" },
  { words: ["油画棒", "蜡笔"], category: "绘画工具" },
  { words: ["朗诵", "演讲"], category: "语言表演" },
  { words: ["提醒", "警告"], category: "提示表达" },
  { words: ["讨论", "辩论"], category: "沟通方式" },
  { words: ["解释", "演示"], category: "表达方式" },
  { words: ["请求", "询问"], category: "沟通方式" },
  { words: ["毛毛雨", "阵雨"], category: "降雨" },
  { words: ["上游", "下游"], category: "水流方位" },
  { words: ["陶瓷杯", "搪瓷杯"], category: "杯具" },
  { words: ["玻璃花瓶", "陶瓷花瓶"], category: "家居摆件" },
  { words: ["地毯", "地垫"], category: "地面织物" },
  { words: ["衣帽架", "鞋架"], category: "家具" },
  { words: ["海绵", "百洁布"], category: "清洁工具" },
  { words: ["蒸汽熨斗", "挂烫机"], category: "熨烫电器" },
  { words: ["登机口", "安检口"], category: "机场区域" },
  { words: ["站票", "卧铺票"], category: "火车票" },
  { words: ["护照夹", "证件包"], category: "旅行收纳" },
  { words: ["古镇", "古村"], category: "传统聚落" },
  { words: ["岛屿", "半岛"], category: "海岸地貌" },
  { words: ["盆栽", "插花"], category: "植物装饰" },
  { words: ["书签", "书套"], category: "阅读配件" },
  { words: ["章节", "目录"], category: "书籍结构" },
  { words: ["书评", "影评"], category: "评论文章" },
  { words: ["预告片", "花絮"], category: "影视内容" },
  { words: ["票根", "纪念章"], category: "旅行纪念" },
  { words: ["纪念币", "邮票"], category: "收藏品" },
  { words: ["陶笛", "口琴"], category: "小型乐器" },
  { words: ["切达奶酪", "马苏里拉", "帕玛森", "蓝纹奶酪"], category: "奶酪品种" },
  { words: ["意大利面", "通心粉", "千层面", "意式饺子"], category: "意式面食" },
  { words: ["天妇罗", "寿喜烧", "章鱼烧", "大阪烧"], category: "日本料理" },
  { words: ["泡菜", "石锅拌饭", "部队锅", "紫菜包饭"], category: "韩国料理" },
  { words: ["冬阴功汤", "咖喱饭", "越南河粉", "海南鸡饭"], category: "东南亚料理" },
  { words: ["提拉米苏", "舒芙蕾", "焦糖布丁", "巴斯克蛋糕"], category: "西式甜点" },
  { words: ["川菜", "粤菜", "鲁菜", "淮扬菜"], category: "中国菜系" },
  { words: ["千与千寻", "龙猫", "天空之城", "哈尔的移动城堡", "幽灵公主"], category: "宫崎骏动画" },
  { words: ["玩具总动员", "海底总动员", "机器人总动员", "飞屋环游记", "寻梦环游记"], category: "皮克斯动画" },
  { words: ["甄嬛传", "琅琊榜", "庆余年", "知否知否应是绿肥红瘦", "长安十二时辰"], category: "国产古装剧" },
  { words: ["开端", "隐秘的角落", "漫长的季节", "沉默的真相", "白夜追凶"], category: "国产悬疑剧" },
  { words: ["天龙八部", "射雕英雄传", "神雕侠侣", "倚天屠龙记", "笑傲江湖"], category: "金庸武侠作品" },
  { words: ["大话西游", "功夫", "少林足球", "喜剧之王", "食神"], category: "周星驰电影" },
  { words: ["警察故事", "醉拳", "尖峰时刻", "十二生肖", "红番区"], category: "成龙电影" },
  { words: ["盗梦空间", "星际穿越", "信条", "奥本海默", "蝙蝠侠：黑暗骑士"], category: "诺兰电影" },
  { words: ["黑客帝国", "阿凡达", "银翼杀手", "沙丘", "流浪地球"], category: "科幻电影" },
  { words: ["后天", "2012", "海啸奇迹", "地心引力", "全球风暴"], category: "灾难电影" },
  { words: ["看不见的客人", "利刃出鞘", "东方快车谋杀案", "误杀", "唐人街探案"], category: "悬疑电影" },
  { words: ["哈利·波特", "赫敏", "罗恩", "邓布利多", "伏地魔", "斯内普"], category: "哈利波特人物" },
  { words: ["唐僧", "沙僧", "白龙马", "观音菩萨", "玉皇大帝"], category: "西游记人物" },
  { words: ["曹操", "刘备", "孙权", "诸葛亮", "周瑜", "司马懿"], category: "三国人物" },
  { words: ["贾宝玉", "林黛玉", "薛宝钗", "王熙凤", "史湘云"], category: "红楼梦人物" },
  { words: ["福尔摩斯", "波洛", "柯南", "金田一", "狄仁杰"], category: "侦探角色" },
  { words: ["呐喊", "彷徨", "朝花夕拾", "野草"], category: "鲁迅作品" },
  { words: ["鲁迅", "老舍", "巴金", "茅盾", "沈从文"], category: "中国现代作家" },
  { words: ["莎士比亚", "雨果", "托尔斯泰", "海明威", "马克·吐温"], category: "外国作家" },
  { words: ["秦始皇", "汉武帝", "唐太宗", "宋太祖", "明太祖", "康熙"], category: "中国帝王" },
  { words: ["古埃及", "古希腊", "古罗马", "古巴比伦"], category: "古代文明" },
  { words: ["春秋", "战国", "三国", "南北朝"], category: "中国历史时期" },
  { words: ["长江", "黄河", "尼罗河", "亚马孙河", "多瑙河"], category: "世界河流" },
  { words: ["鄱阳湖", "洞庭湖", "太湖", "洪泽湖", "青海湖"], category: "中国湖泊" },
  { words: ["泰山", "华山", "黄山", "峨眉山", "庐山"], category: "中国名山" },
  { words: ["伦敦", "巴黎", "柏林", "罗马", "马德里"], category: "欧洲首都" },
  { words: ["东京", "首尔", "曼谷", "新加坡", "河内"], category: "亚洲城市" },
  { words: ["Windows", "macOS", "Linux", "Android", "iOS"], category: "操作系统" },
  { words: ["Chrome", "Edge", "Firefox", "Safari", "Opera"], category: "网页浏览器" },
  { words: ["Python", "Java", "C++", "JavaScript", "Go", "Rust"], category: "编程语言" },
  { words: ["PDF", "Word", "Excel", "PPT", "TXT"], category: "文档格式" },
  { words: ["JPEG", "PNG", "GIF", "WebP", "SVG"], category: "图像格式" },
  { words: ["处理器", "显卡", "内存", "硬盘", "主板", "电源"], category: "电脑硬件" },
  { words: ["交换机", "光猫", "无线网卡", "网线"], category: "网络设备" },
  { words: ["聊天机器人", "图像生成", "语音识别", "机器翻译"], category: "人工智能应用" },
  { words: ["温度传感器", "光线传感器", "陀螺仪", "加速度计"], category: "电子传感器" },
  { words: ["太阳能", "风能", "水能", "地热能"], category: "可再生能源" },
  { words: ["印象派", "现实主义", "浪漫主义", "超现实主义"], category: "艺术流派" },
  { words: ["拉丁舞", "街舞", "爵士舞", "民族舞"], category: "舞蹈类型" },
  { words: ["生", "旦", "净", "丑"], category: "戏曲行当" },
  { words: ["流行音乐", "摇滚乐", "爵士乐", "古典音乐", "电子音乐"], category: "音乐类型" },
  { words: ["人像摄影", "风光摄影", "街头摄影", "静物摄影"], category: "摄影题材" },
  { words: ["科幻小说", "推理小说", "武侠小说", "言情小说"], category: "小说类型" },
  { words: ["同学", "同事", "邻居", "室友"], category: "社会关系" },
  { words: ["现金支付", "刷卡支付", "扫码支付", "转账"], category: "支付方式" },
  { words: ["快递", "同城配送", "外卖", "跑腿"], category: "配送服务" },
  { words: ["自由行", "跟团游", "自驾游", "背包旅行"], category: "旅行方式" },
  { words: ["靠窗座", "过道座", "前排座", "后排座"], category: "座位类型" },
  { words: ["硬座", "软座", "硬卧", "软卧", "商务座"], category: "火车席别" },
  { words: ["值机", "托运", "安检", "登机"], category: "乘机流程" },
  { words: ["将", "士", "象", "车", "马", "炮"], category: "中国象棋棋子" },
  { words: ["万子", "筒子", "条子", "风牌", "箭牌"], category: "麻将牌类别" },
  { words: ["超级马里奥", "塞尔达传说", "宝可梦", "动物森友会", "斯普拉遁"], category: "任天堂游戏" },
  { words: ["我的世界", "泰拉瑞亚", "饥荒", "星露谷物语"], category: "沙盒生存游戏" },
  { words: ["反恐精英", "使命召唤", "战地", "守望先锋", "无畏契约"], category: "射击游戏" },
  { words: ["上路", "中路", "下路", "打野", "辅助"], category: "MOBA位置" },
  { words: ["前端工程师", "后端工程师", "测试工程师", "运维工程师", "产品经理"], category: "互联网岗位" },
  { words: ["内科医生", "外科医生", "儿科医生", "眼科医生", "口腔科医生"], category: "医生科室" },
  { words: ["编剧", "剪辑师", "摄影指导", "灯光师", "录音师"], category: "影视制作职业" },
  { words: ["律师", "法官", "检察官", "书记员"], category: "司法职业" },
  { words: ["苏轼", "辛弃疾", "李清照", "柳永", "陆游"], category: "宋代词人" },
  { words: ["兰亭集序", "祭侄文稿", "寒食帖", "快雪时晴帖"], category: "书法名帖" },
  { words: ["清明上河图", "千里江山图", "富春山居图", "洛神赋图"], category: "中国名画" },
  { words: ["青花瓷", "粉彩瓷", "珐琅彩", "汝窑瓷"], category: "中国瓷器" },
  { words: ["长城", "大运河", "都江堰", "灵渠"], category: "古代工程" },
  { words: ["路易吉", "耀西", "奇诺比奥", "库巴", "碧姬公主"], category: "马里奥角色" },
  { words: ["皮卡丘", "喷火龙", "杰尼龟", "妙蛙种子", "伊布"], category: "宝可梦角色" },
  { words: ["米老鼠", "唐老鸭", "高飞", "布鲁托", "黛丝"], category: "迪士尼经典角色" },
  { words: ["哆啦A梦", "大雄", "静香", "胖虎", "小夫"], category: "哆啦A梦人物" },
  { words: ["江户川柯南", "毛利兰", "灰原哀", "毛利小五郎", "怪盗基德"], category: "名侦探柯南人物" },
];

const CHALLENGING_WORD_GROUPS: readonly WordGroupEntry[] = [
  { words: ["拿铁", "卡布奇诺"], category: "咖啡" },
  { words: ["美式咖啡", "冷萃咖啡"], category: "咖啡" },
  { words: ["茉莉花茶", "菊花茶"], category: "花茶" },
  { words: ["珍珠奶茶", "椰果奶茶"], category: "奶茶品类" },
  { words: ["气泡水", "苏打水"], category: "碳酸水" },
  { words: ["黄酒", "米酒"], category: "米酿酒" },
  { words: ["甘蔗汁", "椰子水"], category: "天然饮品" },
  { words: ["肉夹馍", "驴肉火烧"], category: "地方小吃" },
  { words: ["锅贴", "煎饺"], category: "煎制面点" },
  { words: ["葱油饼", "手抓饼"], category: "饼类" },
  { words: ["煎饼果子", "鸡蛋灌饼"], category: "早餐小吃" },
  { words: ["豚骨拉面", "味噌拉面"], category: "日式拉面" },
  { words: ["担担面", "重庆小面"], category: "川渝面食" },
  { words: ["叉烧包", "流沙包"], category: "广式点心" },
  { words: ["蛋挞", "泡芙"], category: "烘焙甜点" },
  { words: ["慕斯蛋糕", "芝士蛋糕"], category: "西式甜点" },
  { words: ["马卡龙", "曲奇"], category: "西式点心" },
  { words: ["香菜", "芹菜"], category: "香味蔬菜" },
  { words: ["韭菜", "蒜苗"], category: "香味蔬菜" },
  { words: ["生姜", "大蒜"], category: "辛香食材" },
  { words: ["青花椒", "红花椒"], category: "花椒" },
  { words: ["孜然", "迷迭香"], category: "香料" },
  { words: ["罗勒", "薄荷"], category: "香草" },
  { words: ["芝麻油", "花生油"], category: "食用油" },
  { words: ["蚝油", "鱼露"], category: "鲜味调料" },
  { words: ["淀粉", "面粉"], category: "烹饪粉类" },
  { words: ["糯米", "粳米"], category: "米类" },
  { words: ["羊毛衫", "羊绒衫"], category: "针织上装" },
  { words: ["冲锋衣", "雨衣"], category: "防水外套" },
  { words: ["皮靴", "马丁靴"], category: "靴子" },
  { words: ["乐福鞋", "牛津鞋"], category: "皮鞋" },
  { words: ["阔腿裤", "直筒裤"], category: "裤型" },
  { words: ["丝巾", "披肩"], category: "颈部配饰" },
  { words: ["平板电脑", "电子书阅读器"], category: "阅读设备" },
  { words: ["机械键盘", "薄膜键盘"], category: "键盘" },
  { words: ["单反相机", "微单相机"], category: "相机" },
  { words: ["移动硬盘", "固态硬盘"], category: "存储设备" },
  { words: ["无线路由器", "信号放大器"], category: "网络设备" },
  { words: ["智能音箱", "蓝牙音箱"], category: "音响" },
  { words: ["宣纸", "素描纸"], category: "绘画纸张" },
  { words: ["月牙", "月食"], category: "月球景象" },
  { words: ["冰川", "雪山"], category: "冰雪地貌" },
  { words: ["钟乳石", "石笋"], category: "洞穴地貌" },
  { words: ["红树林", "湿地"], category: "生态环境" },
  { words: ["珊瑚礁", "海草床"], category: "海洋生态" },
  { words: ["榕树", "梧桐树"], category: "常见树木" },
  { words: ["花豹", "猎豹"], category: "猫科动物" },
  { words: ["梅花鹿", "麋鹿"], category: "鹿类" },
  { words: ["野马", "斑马"], category: "马科动物" },
  { words: ["信天翁", "海燕"], category: "海鸟" },
  { words: ["蚂蚁", "白蚁"], category: "群居昆虫" },
  { words: ["青年旅舍", "客栈"], category: "旅行住宿" },
  { words: ["古董店", "旧书店"], category: "特色商店" },
  { words: ["展览馆", "会展中心"], category: "展会场地" },
  { words: ["音乐厅", "歌剧院"], category: "演出场馆" },
  { words: ["茶馆", "咖啡馆"], category: "饮品场所" },
  { words: ["街角咖啡馆", "连锁咖啡店"], category: "咖啡场所" },
  { words: ["冲浪板", "滑水板"], category: "水上器材" },
  { words: ["双板滑雪", "单板滑雪"], category: "滑雪方式" },
  { words: ["攀岩鞋", "登山鞋"], category: "户外鞋" },
  { words: ["乒乓球台", "台球桌"], category: "球桌" },
  { words: ["水墨画", "工笔画"], category: "国画" },
  { words: ["版画", "木刻"], category: "印刷艺术" },
  { words: ["二胡", "琵琶"], category: "民族弦乐" },
  { words: ["古筝", "扬琴"], category: "民族乐器" },
  { words: ["笛子", "箫"], category: "民族管乐" },
  { words: ["京剧", "昆曲"], category: "戏曲" },
  { words: ["相声", "小品"], category: "曲艺" },
  { words: ["心理医生", "心理咨询师"], category: "心理职业" },
  { words: ["兽医", "宠物美容师"], category: "宠物职业" },
  { words: ["验光师", "配镜师"], category: "眼镜职业" },
  { words: ["甜品师", "面包师"], category: "烘焙职业" },
  { words: ["调酒师", "咖啡师"], category: "饮品职业" },
  { words: ["翻译", "校对"], category: "文字工作" },
  { words: ["导演", "制片人"], category: "影视职业" },
  { words: ["策展人", "讲解员"], category: "展览职业" },
  { words: ["木匠", "家具设计师"], category: "家具职业" },
  { words: ["花艺师", "园艺师"], category: "植物职业" },
  { words: ["夸奖", "鼓励"], category: "正向表达" },
  { words: ["同意", "妥协"], category: "态度" },
  { words: ["犹豫", "纠结"], category: "决策状态" },
  { words: ["怀疑", "猜测"], category: "判断状态" },
  { words: ["安慰", "支持"], category: "情感支持" },
  { words: ["惊喜", "惊讶"], category: "情绪" },
  { words: ["暴雨", "雷雨"], category: "强降雨" },
  { words: ["霜冻", "冰雹"], category: "冰冻天气" },
  { words: ["清晨", "上午"], category: "白天时段" },
  { words: ["黄昏", "夜晚"], category: "一日时段" },
  { words: ["香薰蜡烛", "香薰精油"], category: "香氛用品" },
  { words: ["置物架", "收纳箱"], category: "收纳用品" },
  { words: ["钢丝球", "刷子"], category: "清洁工具" },
  { words: ["除湿机", "干衣机"], category: "家用电器" },
  { words: ["行程单", "确认单"], category: "旅行凭证" },
  { words: ["城市地标", "历史遗址"], category: "旅行景点" },
  { words: ["瀑布", "峡谷"], category: "自然景区" },
  { words: ["骑楼", "牌坊"], category: "建筑景观" },
  { words: ["唐朝", "宋朝", "明朝", "清朝"], category: "朝代" },
  { words: ["手冲咖啡", "挂耳咖啡"], category: "咖啡冲泡方式" },
  { words: ["大红袍", "铁观音"], category: "名茶" },
  { words: ["朗姆酒", "龙舌兰"], category: "烈酒" },
  { words: ["怀石料理", "会席料理"], category: "日式高端料理" },
  { words: ["吊脚楼", "四合院"], category: "传统民居" },
  { words: ["雅丹地貌", "丹霞地貌"], category: "特殊地貌" },
  { words: ["日全食", "日环食"], category: "日食类型" },
  { words: ["蓝鲸", "座头鲸"], category: "鲸类" },
  { words: ["螳螂", "蟑螂"], category: "昆虫" },
  { words: ["审计师", "精算师"], category: "金融职业" },
  { words: ["机器学习", "深度学习"], category: "人工智能技术" },
  { words: ["通货膨胀", "通货紧缩"], category: "经济现象" },
  { words: ["潜意识", "直觉"], category: "心理概念" },
  { words: ["随笔", "杂文"], category: "文学体裁" },
  { words: ["磁悬浮列车", "轻轨"], category: "轨道交通" },
  { words: ["引体向上", "俯卧撑"], category: "徒手训练" },
  { words: ["阿司匹林", "布洛芬"], category: "解热镇痛药" },
  { words: ["胡辣汤", "油茶"], category: "地方早点" },
  { words: ["越剧", "黄梅戏"], category: "地方戏曲" },
  { words: ["腊八节", "小年"], category: "年节习俗" },
  { words: ["孔子", "孟子", "老子", "庄子"], category: "先秦思想家" },
  { words: ["赤壁之战", "官渡之战", "淝水之战"], category: "历史战役" },
  { words: ["昆仑山", "天山", "祁连山"], category: "西部名山" },
  { words: ["甲骨文", "金文", "小篆"], category: "古代文字" },
  { words: ["李白", "杜甫", "白居易", "王维", "孟浩然", "岑参", "高适", "王昌龄"], category: "唐代诗人" },
  { words: ["芥末", "辣根"], category: "辛香调料" },
  { words: ["路由器", "调制解调器"], category: "网络设备" },
  { words: ["车轮", "轮胎"], category: "车辆部件" },
  { words: ["排骨", "肋排"], category: "肉排部位" },
  { words: ["大排档", "路边摊"], category: "市井餐饮" },
  { words: ["洗洁精", "清洁剂"], category: "清洁用品" },
  { words: ["体操", "艺术体操"], category: "竞技体操" },
  { words: ["TCP", "UDP"], category: "传输层协议" },
  { words: ["HTTP", "HTTPS"], category: "网页协议" },
  { words: ["IPv4", "IPv6"], category: "互联网协议版本" },
  { words: ["局域网", "广域网"], category: "网络范围" },
  { words: ["进程", "线程"], category: "操作系统概念" },
  { words: ["栈", "队列"], category: "数据结构" },
  { words: ["树", "图"], category: "数据结构" },
  { words: ["数组", "链表"], category: "线性数据结构" },
  { words: ["编译", "解释"], category: "程序执行方式" },
  { words: ["同步", "异步"], category: "程序执行模式" },
  { words: ["并发", "并行"], category: "计算方式" },
  { words: ["加密", "哈希"], category: "数据安全技术" },
  { words: ["身份认证", "权限授权"], category: "访问控制" },
  { words: ["客户端", "服务器"], category: "网络架构角色" },
  { words: ["SQL", "NoSQL"], category: "数据库类型" },
  { words: ["主键", "外键"], category: "数据库键" },
  { words: ["索引", "视图"], category: "数据库对象" },
  { words: ["GET", "POST"], category: "HTTP请求方法" },
  { words: ["REST", "GraphQL"], category: "接口架构" },
  { words: ["内存", "只读存储器"], category: "计算机存储" },
  { words: ["缓存", "寄存器"], category: "高速存储" },
  { words: ["CPU", "GPU", "NPU"], category: "计算处理器" },
  { words: ["固态硬盘", "机械硬盘"], category: "硬盘类型" },
  { words: ["OLED", "Mini-LED"], category: "显示技术" },
  { words: ["位图", "矢量图"], category: "图像类型" },
  { words: ["RGB", "CMYK"], category: "色彩模式" },
  { words: ["无损压缩", "有损压缩"], category: "压缩方式" },
  { words: ["开源软件", "闭源软件"], category: "软件授权模式" },
  { words: ["本地计算", "云计算"], category: "计算部署方式" },
  { words: ["监督学习", "无监督学习"], category: "机器学习范式" },
  { words: ["分类", "回归"], category: "机器学习任务" },
  { words: ["准确率", "召回率"], category: "模型评估指标" },
  { words: ["过拟合", "欠拟合"], category: "模型训练问题" },
  { words: ["训练", "推理"], category: "人工智能流程" },
  { words: ["参数", "超参数"], category: "模型配置" },
  { words: ["特征", "标签"], category: "机器学习数据" },
  { words: ["词元", "嵌入"], category: "自然语言处理概念" },
  { words: ["提示词", "上下文窗口"], category: "大模型概念" },
  { words: ["检索增强生成", "微调"], category: "大模型增强方式" },
  { words: ["编码器", "解码器"], category: "神经网络模块" },
  { words: ["生成模型", "判别模型"], category: "机器学习模型" },
  { words: ["结构化数据", "非结构化数据"], category: "数据形态" },
  { words: ["财政政策", "货币政策"], category: "宏观经济政策" },
  { words: ["股票", "债券"], category: "金融资产" },
  { words: ["现货", "期货"], category: "交易品种" },
  { words: ["一级市场", "二级市场"], category: "资本市场" },
  { words: ["资产", "负债"], category: "会计要素" },
  { words: ["营业收入", "净利润"], category: "企业财务指标" },
  { words: ["毛利润", "净利润"], category: "利润指标" },
  { words: ["供给", "需求"], category: "经济学概念" },
  { words: ["垄断", "寡头垄断"], category: "市场结构" },
  { words: ["经济衰退", "经济萧条"], category: "经济周期" },
  { words: ["汇率", "利率"], category: "金融指标" },
  { words: ["名义GDP", "实际GDP"], category: "国内生产总值" },
  { words: ["CPI", "PPI"], category: "价格指数" },
  { words: ["牛市", "熊市"], category: "市场行情" },
  { words: ["民事案件", "刑事案件"], category: "案件类型" },
  { words: ["原告", "被告"], category: "诉讼当事人" },
  { words: ["控方", "辩方"], category: "刑事诉讼角色" },
  { words: ["上诉", "再审"], category: "司法救济程序" },
  { words: ["证人", "鉴定人"], category: "诉讼参与人" },
  { words: ["法律", "行政法规"], category: "法律规范" },
  { words: ["宪法", "普通法律"], category: "法律层级" },
  { words: ["公投", "选举"], category: "政治参与方式" },
  { words: ["细菌", "病毒"], category: "病原体" },
  { words: ["抗体", "抗原"], category: "免疫学概念" },
  { words: ["动脉", "静脉"], category: "血管类型" },
  { words: ["CT", "核磁共振"], category: "医学影像检查" },
  { words: ["X光", "超声"], category: "医学检查" },
  { words: ["收缩压", "舒张压"], category: "血压指标" },
  { words: ["急性病", "慢性病"], category: "疾病病程" },
  { words: ["良性肿瘤", "恶性肿瘤"], category: "肿瘤性质" },
  { words: ["诊断", "鉴别诊断"], category: "临床判断" },
  { words: ["处方药", "非处方药"], category: "药品类型" },
  { words: ["过敏", "不耐受"], category: "身体反应" },
  { words: ["DNA", "RNA"], category: "遗传物质" },
  { words: ["有丝分裂", "减数分裂"], category: "细胞分裂" },
  { words: ["原子", "分子"], category: "物质结构" },
  { words: ["同位素", "离子"], category: "原子相关概念" },
  { words: ["酸", "碱"], category: "化学性质" },
  { words: ["氧化", "还原"], category: "化学反应" },
  { words: ["导体", "绝缘体"], category: "电学材料" },
  { words: ["质量", "重量"], category: "物理量" },
  { words: ["速率", "速度"], category: "运动学概念" },
  { words: ["功率", "能量"], category: "物理量" },
  { words: ["频率", "振幅"], category: "波动参数" },
  { words: ["折射", "反射"], category: "光学现象" },
  { words: ["串联电路", "并联电路"], category: "电路连接" },
  { words: ["纬度", "经度"], category: "地理坐标" },
  { words: ["天气", "气候"], category: "大气概念" },
  { words: ["三角洲", "河口"], category: "河流地貌" },
  { words: ["分水岭", "流域"], category: "水文地理" },
  { words: ["公转", "自转"], category: "天体运动" },
  { words: ["近日点", "远日点"], category: "轨道位置" },
  { words: ["小行星", "彗星"], category: "太阳系小天体" },
  { words: ["日食", "月食"], category: "天文现象" },
  { words: ["比喻", "借代"], category: "修辞手法" },
  { words: ["反讽", "讽刺"], category: "表达手法" },
  { words: ["散文", "韵文"], category: "文体形式" },
  { words: ["长篇小说", "中篇小说"], category: "小说篇幅" },
  { words: ["第一人称", "第三人称"], category: "叙事视角" },
  { words: ["主句", "从句"], category: "句法结构" },
  { words: ["主动语态", "被动语态"], category: "语法语态" },
  { words: ["繁体字", "简体字"], category: "汉字字形" },
  { words: ["衬线字体", "无衬线字体"], category: "字体类型" },
  { words: ["字距", "行距"], category: "文字排版" },
  { words: ["节拍", "节奏"], category: "音乐概念" },
  { words: ["旋律", "和声"], category: "音乐要素" },
  { words: ["大调", "小调"], category: "调式" },
  { words: ["独奏", "合奏"], category: "演奏形式" },
  { words: ["续集", "前传"], category: "影视作品关系" },
  { words: ["客串", "特别出演"], category: "演员参与方式" },
  { words: ["剧本", "分镜"], category: "影视前期制作" },
  { words: ["剪辑", "蒙太奇"], category: "影视编辑" },
  { words: ["远景", "特写"], category: "镜头景别" },
  { words: ["光圈", "快门", "感光度"], category: "摄影曝光参数" },
  { words: ["焦距", "景深"], category: "摄影参数" },
  { words: ["RAW", "JPEG"], category: "照片格式" },
  { words: ["光学变焦", "数字变焦"], category: "变焦方式" },
  { words: ["定焦镜头", "变焦镜头"], category: "摄影镜头" },
  { words: ["广角镜头", "长焦镜头"], category: "镜头焦段" },
  { words: ["律诗", "绝句"], category: "近体诗" },
  { words: ["平仄", "押韵"], category: "诗词格律" },
  { words: ["本纪", "列传"], category: "纪传体史书篇目" },
  { words: ["编年体", "纪传体"], category: "史书体例" },
  { words: ["儒家", "道家"], category: "先秦学派" },
  { words: ["察举制", "科举制"], category: "古代选官制度" },
  { words: ["分封制", "郡县制"], category: "古代地方制度" },
  { words: ["豪放派", "婉约派"], category: "宋词流派" },
  { words: ["工笔", "写意"], category: "中国画技法" },
  { words: ["篆书", "隶书", "楷书", "行书", "草书"], category: "书法字体" },
  { words: ["巴洛克", "洛可可"], category: "欧洲艺术风格" },
  { words: ["哥特式建筑", "罗马式建筑"], category: "欧洲建筑风格" },
  { words: ["协奏曲", "交响曲"], category: "古典音乐体裁" },
  { words: ["奏鸣曲", "圆舞曲"], category: "音乐体裁" },
  { words: ["莎士比亚", "塞万提斯", "歌德", "但丁"], category: "欧洲古典作家" },
  { words: ["达·芬奇", "米开朗琪罗", "拉斐尔", "提香"], category: "文艺复兴艺术家" },
  { words: ["苏格拉底", "柏拉图", "亚里士多德"], category: "古希腊哲学家" },
  { words: ["韩愈", "柳宗元", "欧阳修", "苏轼"], category: "唐宋散文家" },
  { words: ["王羲之", "颜真卿", "柳公权", "赵孟頫"], category: "中国书法家" },
];

export const WORD_GROUPS: readonly WordGroup[] = [
  ...createWordGroups(1, EASY_WORD_GROUPS),
  ...createWordGroups(2, STANDARD_WORD_GROUPS),
  ...createWordGroups(3, CHALLENGING_WORD_GROUPS),
];